FROM alpine:3.19.1

RUN  apk update \
  && apk upgrade \
  && apk add ca-certificates \
  && update-ca-certificates \
  && apk add --update coreutils && rm -rf /var/cache/apk/*   \ 
  && apk add --update openjdk21 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing \
  && apk add --no-cache nss \
  && rm -rf /var/cache/apk/*

COPY Hello.java Hello.java

RUN javac Hello.java

CMD ["java", "Hello"]
