FROM alpine:3.18

RUN  apk update \
  && apk upgrade \
  && apk add ca-certificates \
  && update-ca-certificates \
  && apk add --update coreutils && rm -rf /var/cache/apk/*   \ 
  && apk add --update openjdk20 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing \
  && apk add --no-cache nss \
  && rm -rf /var/cache/apk/*

WORKDIR /

COPY App.java /App.java

RUN javac --enable-preview --source 20 App.java

CMD ["java", "--enable-preview", "App"]